export const PAGE_SIZE = 10;

export const ROWS_PER_PAGE = [5, 10, 15, 30, 50];

export const queryKeys = {
  BOOKINGS: ["BOOKINGS", PAGE_SIZE],
  BOOKING_STATS: ["BOOKING_STATS"],
  PROPERTIES: ["PROPERTIES", PAGE_SIZE],
  NOTIFICATIONS: ["NOTIFICATIONS", PAGE_SIZE],
  PROPERTIES_SEARCH: "PROPERTIES_SEARCH",
  PROPERTY: "PROPERTY",
  FEATURED_PROPERTIES: ["FEATURED_PROPERTIES", PAGE_SIZE],
  USERS: ["USERS", PAGE_SIZE],
};

export const AMENITIES = ["WiFi", "Kitchen", "Free parking", "Pool"];
